### ISSUE TITLE
Adding support for Ed25519 signatures

### ISSUE THREAD

**Issue by skion** [progrium/pyjwt#42]
Would anyone upstream be interested in adding support for NaCl-style [Ed25519](http://ed25519.cr.yp.to/) signatures? I have done some preliminary work [in here](https://github.com/skion/pyjwt/tree/nacl-pure) based on [PyNaCl](https://github.com/pyca/pynacl). At the moment it includes a fallback (and prohibitively slow) pure-Python implementation as well, but I could easily be persuaded to create a PR without that part and/or based on feedback.

**Comment by wbolster** [comment]
@skion see #70 for more discussion re. extensions.

**Comment by mark-adams** [comment]
@jpadilla Since we've decided this is best handled by some form of extensibility (like #70), can we go ahead and close this issue?

**Comment by skion** [comment]
Most definitely; looking forward to trying the registry stuff soon.

**Comment by stela** [comment]
Since January 2017, Ed25519 and Ed448 signatures are now standardized by this RFC: https://tools.ietf.org/html/rfc8037 (using alg=EdDSA)
There's a registry of algorithm definitions to use for JOSE implementations at https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms
